docker stop nginx
docker stop gateway
docker stop auth
docker stop checkcode
docker stop learning
docker stop content
docker stop system
docker stop media
docker stop orders
docker stop search

docker start gateway
docker start auth
docker start checkcode
docker start learning
docker start content
docker start system
docker start media
docker start orders
docker start search
docker start nginx