FROM nginx:1.24.0

COPY nginx.conf /etc/nginx/nginx.conf

COPY html  /etc/nginx/html

#RUN mkdir /etc/nginx/cert

#COPY www.yefan.xyz.pem /etc/nginx/cert/www.yefan.xyz.pem

#COPY www.yefan.xyz.key /etc/nginx/cert/www.yefan.xyz.key

EXPOSE 80
