### 申请令牌
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=authorization_code&code=7ETkUb&redirect_uri=http://www.yefan.xyz

### http://localhost:8085/auth/oauth/authorize?client_id=XcWebApp&response_type=code&scope=all&redirect_uri=http://www.yefan.xyz
### /oauth/authorize?client_id=XcWebApp&response_type=code&scope=all&redirect_uri=http://www.yefan.xyz

### 密码模式
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username={"username":"admin", "password":"111111", "authType":"password"}

### 校验jwt令牌
POST {{auth_host}}/auth/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJjb21wYW55SWRcIjpcIjEyMzIxNDE0MjVcIixcImNyZWF0ZVRpbWVcIjpcIjIwMjItMDktMjhUMDg6MzI6MDNcIixcImlkXCI6XCI1MlwiLFwibmFtZVwiOlwiTeiAgeW4iFwiLFwicGVybWlzc2lvbnNcIjpbXSxcInNleFwiOlwiMVwiLFwic3RhdHVzXCI6XCJcIixcInVzZXJuYW1lXCI6XCJ0MVwiLFwidXR5cGVcIjpcIjEwMTAwMlwifSIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2OTU5OTMzMDMsImF1dGhvcml0aWVzIjpbInRlc3QiXSwianRpIjoiMWI5OTU0N2YtMTI1OS00NDFiLWE4NWEtZGU2YWNhZWJlNjhmIiwiY2xpZW50X2lkIjoiWGNXZWJBcHAifQ.TNoS78tiRdOAFLfCpgL3h6baFpCnZOCzgRAUlHMaZoA

###
GET {{gateway_host}}/content/course/124
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJjcmVhdGVUaW1lXCI6XCIyMDIyLTA5LTI4VDA4OjMyOjAzXCIsXCJpZFwiOlwiNDhcIixcIm5hbWVcIjpcIuezu-e7n-euoeeQhuWRmFwiLFwic2V4XCI6XCIxXCIsXCJzdGF0dXNcIjpcIjFcIixcInVzZXJuYW1lXCI6XCJhZG1pblwiLFwidXR5cGVcIjpcIjEwMTAwM1wifSIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2OTU5NjkyMTEsImF1dGhvcml0aWVzIjpbInRlc3QiXSwianRpIjoiNWFlMjM0NDctNTE2MS00OTJiLTllNTctOTAwZDA1MDJkZTRhIiwiY2xpZW50X2lkIjoiWGNXZWJBcHAifQ.m2FQd-YTsdol7L5tAjE-lOCquwHbq-M4GPr6fo9k4n8

